// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: api/pledge/v1/animal.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address     string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	StakeAmount int64  `protobuf:"varint,2,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"`
	Level       int64  `protobuf:"varint,3,opt,name=level,proto3" json:"level,omitempty"`
	Category    int64  `protobuf:"varint,4,opt,name=category,proto3" json:"category,omitempty"`
	Capacity    int64  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Volume      int64  `protobuf:"varint,6,opt,name=volume,proto3" json:"volume,omitempty"`
	Rarity      int64  `protobuf:"varint,7,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Sex         int64  `protobuf:"varint,8,opt,name=sex,proto3" json:"sex,omitempty"`
	Age         int64  `protobuf:"varint,9,opt,name=age,proto3" json:"age,omitempty"`
	TokenId     int64  `protobuf:"varint,10,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *CreateAnimalRequest) Reset() {
	*x = CreateAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimalRequest) ProtoMessage() {}

func (x *CreateAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimalRequest.ProtoReflect.Descriptor instead.
func (*CreateAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAnimalRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreateAnimalRequest) GetStakeAmount() int64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

func (x *CreateAnimalRequest) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *CreateAnimalRequest) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *CreateAnimalRequest) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *CreateAnimalRequest) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *CreateAnimalRequest) GetRarity() int64 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *CreateAnimalRequest) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *CreateAnimalRequest) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *CreateAnimalRequest) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type CreateAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreateAnimalReply) Reset() {
	*x = CreateAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAnimalReply) ProtoMessage() {}

func (x *CreateAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAnimalReply.ProtoReflect.Descriptor instead.
func (*CreateAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAnimalReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreateAnimalReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdateAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAnimalRequest) Reset() {
	*x = UpdateAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnimalRequest) ProtoMessage() {}

func (x *UpdateAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnimalRequest.ProtoReflect.Descriptor instead.
func (*UpdateAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{2}
}

type UpdateAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdateAnimalReply) Reset() {
	*x = UpdateAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateAnimalReply) ProtoMessage() {}

func (x *UpdateAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateAnimalReply.ProtoReflect.Descriptor instead.
func (*UpdateAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{3}
}

type DeleteAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAnimalRequest) Reset() {
	*x = DeleteAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnimalRequest) ProtoMessage() {}

func (x *DeleteAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnimalRequest.ProtoReflect.Descriptor instead.
func (*DeleteAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{4}
}

type DeleteAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeleteAnimalReply) Reset() {
	*x = DeleteAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeleteAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteAnimalReply) ProtoMessage() {}

func (x *DeleteAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteAnimalReply.ProtoReflect.Descriptor instead.
func (*DeleteAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{5}
}

type AnimalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id          int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Address     string `protobuf:"bytes,2,opt,name=address,proto3" json:"address,omitempty"`
	StakeAmount int64  `protobuf:"varint,3,opt,name=stake_amount,json=stakeAmount,proto3" json:"stake_amount,omitempty"`
	Level       int64  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	Category    int64  `protobuf:"varint,5,opt,name=category,proto3" json:"category,omitempty"`
	Capacity    int64  `protobuf:"varint,6,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Volume      int64  `protobuf:"varint,7,opt,name=volume,proto3" json:"volume,omitempty"`
	Rarity      int64  `protobuf:"varint,8,opt,name=rarity,proto3" json:"rarity,omitempty"`
	Sex         int64  `protobuf:"varint,9,opt,name=sex,proto3" json:"sex,omitempty"`
	Age         int64  `protobuf:"varint,10,opt,name=age,proto3" json:"age,omitempty"`
	TokenId     int64  `protobuf:"varint,11,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	ImgUrl      string `protobuf:"bytes,12,opt,name=img_url,json=imgUrl,proto3" json:"img_url,omitempty"`
	Status      int64  `protobuf:"varint,13,opt,name=status,proto3" json:"status,omitempty"`
	StartTime   int64  `protobuf:"varint,14,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
}

func (x *AnimalInfo) Reset() {
	*x = AnimalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AnimalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimalInfo) ProtoMessage() {}

func (x *AnimalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimalInfo.ProtoReflect.Descriptor instead.
func (*AnimalInfo) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{6}
}

func (x *AnimalInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *AnimalInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *AnimalInfo) GetStakeAmount() int64 {
	if x != nil {
		return x.StakeAmount
	}
	return 0
}

func (x *AnimalInfo) GetLevel() int64 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *AnimalInfo) GetCategory() int64 {
	if x != nil {
		return x.Category
	}
	return 0
}

func (x *AnimalInfo) GetCapacity() int64 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *AnimalInfo) GetVolume() int64 {
	if x != nil {
		return x.Volume
	}
	return 0
}

func (x *AnimalInfo) GetRarity() int64 {
	if x != nil {
		return x.Rarity
	}
	return 0
}

func (x *AnimalInfo) GetSex() int64 {
	if x != nil {
		return x.Sex
	}
	return 0
}

func (x *AnimalInfo) GetAge() int64 {
	if x != nil {
		return x.Age
	}
	return 0
}

func (x *AnimalInfo) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *AnimalInfo) GetImgUrl() string {
	if x != nil {
		return x.ImgUrl
	}
	return ""
}

func (x *AnimalInfo) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *AnimalInfo) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

type GetAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId int64 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *GetAnimalRequest) Reset() {
	*x = GetAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalRequest) ProtoMessage() {}

func (x *GetAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalRequest.ProtoReflect.Descriptor instead.
func (*GetAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{7}
}

func (x *GetAnimalRequest) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type GetAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *AnimalInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetAnimalReply) Reset() {
	*x = GetAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnimalReply) ProtoMessage() {}

func (x *GetAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnimalReply.ProtoReflect.Descriptor instead.
func (*GetAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{8}
}

func (x *GetAnimalReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetAnimalReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetAnimalReply) GetData() *AnimalInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Page     int32 `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	PageSize int32 `protobuf:"varint,2,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
}

func (x *ListAnimalRequest) Reset() {
	*x = ListAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnimalRequest) ProtoMessage() {}

func (x *ListAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnimalRequest.ProtoReflect.Descriptor instead.
func (*ListAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{9}
}

func (x *ListAnimalRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListAnimalRequest) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type ListAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string        `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data []*AnimalInfo `protobuf:"bytes,3,rep,name=data,proto3" json:"data,omitempty"`
}

func (x *ListAnimalReply) Reset() {
	*x = ListAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListAnimalReply) ProtoMessage() {}

func (x *ListAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListAnimalReply.ProtoReflect.Descriptor instead.
func (*ListAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{10}
}

func (x *ListAnimalReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ListAnimalReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *ListAnimalReply) GetData() []*AnimalInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type KillAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId int64 `protobuf:"varint,1,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
}

func (x *KillAnimalRequest) Reset() {
	*x = KillAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillAnimalRequest) ProtoMessage() {}

func (x *KillAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillAnimalRequest.ProtoReflect.Descriptor instead.
func (*KillAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{11}
}

func (x *KillAnimalRequest) GetTokenId() int64 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

type KillAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *KillAnimalReply) Reset() {
	*x = KillAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *KillAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KillAnimalReply) ProtoMessage() {}

func (x *KillAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KillAnimalReply.ProtoReflect.Descriptor instead.
func (*KillAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{12}
}

func (x *KillAnimalReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *KillAnimalReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type FeedingAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FromTokenId int64 `protobuf:"varint,1,opt,name=from_token_id,json=fromTokenId,proto3" json:"from_token_id,omitempty"`
	ToTokenId   int64 `protobuf:"varint,2,opt,name=to_token_id,json=toTokenId,proto3" json:"to_token_id,omitempty"`
}

func (x *FeedingAnimalRequest) Reset() {
	*x = FeedingAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedingAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedingAnimalRequest) ProtoMessage() {}

func (x *FeedingAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedingAnimalRequest.ProtoReflect.Descriptor instead.
func (*FeedingAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{13}
}

func (x *FeedingAnimalRequest) GetFromTokenId() int64 {
	if x != nil {
		return x.FromTokenId
	}
	return 0
}

func (x *FeedingAnimalRequest) GetToTokenId() int64 {
	if x != nil {
		return x.ToTokenId
	}
	return 0
}

type FeedingAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *FeedingAnimalReply) Reset() {
	*x = FeedingAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *FeedingAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FeedingAnimalReply) ProtoMessage() {}

func (x *FeedingAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FeedingAnimalReply.ProtoReflect.Descriptor instead.
func (*FeedingAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{14}
}

func (x *FeedingAnimalReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *FeedingAnimalReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type ComposeAnimalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	TokenId1 int64 `protobuf:"varint,1,opt,name=token_id1,json=tokenId1,proto3" json:"token_id1,omitempty"`
	TokenId2 int64 `protobuf:"varint,2,opt,name=token_id2,json=tokenId2,proto3" json:"token_id2,omitempty"`
}

func (x *ComposeAnimalRequest) Reset() {
	*x = ComposeAnimalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeAnimalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeAnimalRequest) ProtoMessage() {}

func (x *ComposeAnimalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeAnimalRequest.ProtoReflect.Descriptor instead.
func (*ComposeAnimalRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{15}
}

func (x *ComposeAnimalRequest) GetTokenId1() int64 {
	if x != nil {
		return x.TokenId1
	}
	return 0
}

func (x *ComposeAnimalRequest) GetTokenId2() int64 {
	if x != nil {
		return x.TokenId2
	}
	return 0
}

type ComposeAnimalReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *ComposeAnimalReply) Reset() {
	*x = ComposeAnimalReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_animal_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ComposeAnimalReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ComposeAnimalReply) ProtoMessage() {}

func (x *ComposeAnimalReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_animal_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ComposeAnimalReply.ProtoReflect.Descriptor instead.
func (*ComposeAnimalReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_animal_proto_rawDescGZIP(), []int{16}
}

func (x *ComposeAnimalReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *ComposeAnimalReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

var File_api_pledge_v1_animal_proto protoreflect.FileDescriptor

var file_api_pledge_v1_animal_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x8f, 0x02, 0x0a, 0x13, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73,
	0x74, 0x61, 0x6b, 0x65, 0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x0b, 0x73, 0x74, 0x61, 0x6b, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14,
	0x0a, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c,
	0x65, 0x76, 0x65, 0x6c, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06,
	0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x76, 0x6f,
	0x6c, 0x75, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03,
	0x73, 0x65, 0x78, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x10,
	0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x0a, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x39, 0x0a, 0x11, 0x43,
	0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79,
	0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04,
	0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x15, 0x0a, 0x13, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a,
	0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70,
	0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x44, 0x65, 0x6c,
	0x65, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0xe6,
	0x02, 0x0a, 0x0a, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a,
	0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x18, 0x0a,
	0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x73, 0x74, 0x61, 0x6b, 0x65,
	0x5f, 0x61, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x73,
	0x74, 0x61, 0x6b, 0x65, 0x41, 0x6d, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x65,
	0x76, 0x65, 0x6c, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x6c, 0x65, 0x76, 0x65, 0x6c,
	0x12, 0x1a, 0x0a, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x08, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x18, 0x06, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08,
	0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x12, 0x16, 0x0a, 0x06, 0x76, 0x6f, 0x6c, 0x75,
	0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x72, 0x61, 0x72, 0x69, 0x74, 0x79, 0x12, 0x10, 0x0a, 0x03, 0x73, 0x65, 0x78, 0x18,
	0x09, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x73, 0x65, 0x78, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67,
	0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x03, 0x52, 0x03, 0x61, 0x67, 0x65, 0x12, 0x19, 0x0a, 0x08,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x0b, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07,
	0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x17, 0x0a, 0x07, 0x69, 0x6d, 0x67, 0x5f, 0x75,
	0x72, 0x6c, 0x18, 0x0c, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x6d, 0x67, 0x55, 0x72, 0x6c,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x0d, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x73, 0x74, 0x61, 0x72,
	0x74, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x0e, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x73, 0x74,
	0x61, 0x72, 0x74, 0x54, 0x69, 0x6d, 0x65, 0x22, 0x2d, 0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x19, 0x0a, 0x08, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x74,
	0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x65, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03,
	0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2d,
	0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61,
	0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x44, 0x0a,
	0x11, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x04, 0x70, 0x61, 0x67, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x70, 0x61, 0x67, 0x65, 0x5f, 0x73,
	0x69, 0x7a, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x08, 0x70, 0x61, 0x67, 0x65, 0x53,
	0x69, 0x7a, 0x65, 0x22, 0x66, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x12, 0x2d, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x2e, 0x0a, 0x11, 0x4b,
	0x69, 0x6c, 0x6c, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x22, 0x37, 0x0a, 0x0f, 0x4b,
	0x69, 0x6c, 0x6c, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x03, 0x6d, 0x73, 0x67, 0x22, 0x5a, 0x0a, 0x14, 0x46, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x22, 0x0a, 0x0d,
	0x66, 0x72, 0x6f, 0x6d, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x0b, 0x66, 0x72, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64,
	0x12, 0x1e, 0x0a, 0x0b, 0x74, 0x6f, 0x5f, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x74, 0x6f, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64,
	0x22, 0x3a, 0x0a, 0x12, 0x46, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73,
	0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x50, 0x0a, 0x14,
	0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64,
	0x31, 0x12, 0x1b, 0x0a, 0x09, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x32, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x32, 0x22, 0x3a,
	0x0a, 0x12, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x32, 0xbc, 0x06, 0x0a, 0x06, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x68, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4,
	0x93, 0x02, 0x0c, 0x22, 0x07, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x3a, 0x01, 0x2a, 0x12,
	0x54, 0x0a, 0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12,
	0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65,
	0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x67, 0x0a, 0x09, 0x47,
	0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70,
	0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e,
	0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14,
	0x12, 0x12, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2f, 0x7b, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x5f, 0x69, 0x64, 0x7d, 0x12, 0x60, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d,
	0x61, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71,
	0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52,
	0x65, 0x70, 0x6c, 0x79, 0x22, 0x10, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x0a, 0x12, 0x08, 0x2f, 0x61,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x73, 0x12, 0x67, 0x0a, 0x0a, 0x4b, 0x69, 0x6c, 0x6c, 0x41, 0x6e,
	0x69, 0x6d, 0x61, 0x6c, 0x12, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x4b, 0x69, 0x6c, 0x6c, 0x41, 0x6e, 0x69, 0x6d, 0x61,
	0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x17, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x11, 0x22, 0x0c,
	0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2f, 0x6b, 0x69, 0x6c, 0x6c, 0x3a, 0x01, 0x2a, 0x12,
	0x73, 0x0a, 0x0d, 0x46, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c,
	0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x46, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x46, 0x65, 0x65, 0x64, 0x69, 0x6e, 0x67, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x14,
	0x22, 0x0f, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2f, 0x66, 0x65, 0x65, 0x64, 0x69, 0x6e,
	0x67, 0x3a, 0x01, 0x2a, 0x12, 0x73, 0x0a, 0x0d, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x41,
	0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x12, 0x23, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x41, 0x6e, 0x69,
	0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x6f, 0x6d, 0x70, 0x6f,
	0x73, 0x65, 0x41, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x1a, 0x82,
	0xd3, 0xe4, 0x93, 0x02, 0x14, 0x22, 0x0f, 0x2f, 0x61, 0x6e, 0x69, 0x6d, 0x61, 0x6c, 0x2f, 0x63,
	0x6f, 0x6d, 0x70, 0x6f, 0x73, 0x65, 0x3a, 0x01, 0x2a, 0x42, 0x2e, 0x0a, 0x0d, 0x61, 0x70, 0x69,
	0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x68, 0x65,
	0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x33,
}

var (
	file_api_pledge_v1_animal_proto_rawDescOnce sync.Once
	file_api_pledge_v1_animal_proto_rawDescData = file_api_pledge_v1_animal_proto_rawDesc
)

func file_api_pledge_v1_animal_proto_rawDescGZIP() []byte {
	file_api_pledge_v1_animal_proto_rawDescOnce.Do(func() {
		file_api_pledge_v1_animal_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pledge_v1_animal_proto_rawDescData)
	})
	return file_api_pledge_v1_animal_proto_rawDescData
}

var file_api_pledge_v1_animal_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_api_pledge_v1_animal_proto_goTypes = []interface{}{
	(*CreateAnimalRequest)(nil),  // 0: api.pledge.v1.CreateAnimalRequest
	(*CreateAnimalReply)(nil),    // 1: api.pledge.v1.CreateAnimalReply
	(*UpdateAnimalRequest)(nil),  // 2: api.pledge.v1.UpdateAnimalRequest
	(*UpdateAnimalReply)(nil),    // 3: api.pledge.v1.UpdateAnimalReply
	(*DeleteAnimalRequest)(nil),  // 4: api.pledge.v1.DeleteAnimalRequest
	(*DeleteAnimalReply)(nil),    // 5: api.pledge.v1.DeleteAnimalReply
	(*AnimalInfo)(nil),           // 6: api.pledge.v1.AnimalInfo
	(*GetAnimalRequest)(nil),     // 7: api.pledge.v1.GetAnimalRequest
	(*GetAnimalReply)(nil),       // 8: api.pledge.v1.GetAnimalReply
	(*ListAnimalRequest)(nil),    // 9: api.pledge.v1.ListAnimalRequest
	(*ListAnimalReply)(nil),      // 10: api.pledge.v1.ListAnimalReply
	(*KillAnimalRequest)(nil),    // 11: api.pledge.v1.KillAnimalRequest
	(*KillAnimalReply)(nil),      // 12: api.pledge.v1.KillAnimalReply
	(*FeedingAnimalRequest)(nil), // 13: api.pledge.v1.FeedingAnimalRequest
	(*FeedingAnimalReply)(nil),   // 14: api.pledge.v1.FeedingAnimalReply
	(*ComposeAnimalRequest)(nil), // 15: api.pledge.v1.ComposeAnimalRequest
	(*ComposeAnimalReply)(nil),   // 16: api.pledge.v1.ComposeAnimalReply
}
var file_api_pledge_v1_animal_proto_depIdxs = []int32{
	6,  // 0: api.pledge.v1.GetAnimalReply.data:type_name -> api.pledge.v1.AnimalInfo
	6,  // 1: api.pledge.v1.ListAnimalReply.data:type_name -> api.pledge.v1.AnimalInfo
	0,  // 2: api.pledge.v1.Animal.CreateAnimal:input_type -> api.pledge.v1.CreateAnimalRequest
	2,  // 3: api.pledge.v1.Animal.UpdateAnimal:input_type -> api.pledge.v1.UpdateAnimalRequest
	4,  // 4: api.pledge.v1.Animal.DeleteAnimal:input_type -> api.pledge.v1.DeleteAnimalRequest
	7,  // 5: api.pledge.v1.Animal.GetAnimal:input_type -> api.pledge.v1.GetAnimalRequest
	9,  // 6: api.pledge.v1.Animal.ListAnimal:input_type -> api.pledge.v1.ListAnimalRequest
	11, // 7: api.pledge.v1.Animal.KillAnimal:input_type -> api.pledge.v1.KillAnimalRequest
	13, // 8: api.pledge.v1.Animal.FeedingAnimal:input_type -> api.pledge.v1.FeedingAnimalRequest
	15, // 9: api.pledge.v1.Animal.ComposeAnimal:input_type -> api.pledge.v1.ComposeAnimalRequest
	1,  // 10: api.pledge.v1.Animal.CreateAnimal:output_type -> api.pledge.v1.CreateAnimalReply
	3,  // 11: api.pledge.v1.Animal.UpdateAnimal:output_type -> api.pledge.v1.UpdateAnimalReply
	5,  // 12: api.pledge.v1.Animal.DeleteAnimal:output_type -> api.pledge.v1.DeleteAnimalReply
	8,  // 13: api.pledge.v1.Animal.GetAnimal:output_type -> api.pledge.v1.GetAnimalReply
	10, // 14: api.pledge.v1.Animal.ListAnimal:output_type -> api.pledge.v1.ListAnimalReply
	12, // 15: api.pledge.v1.Animal.KillAnimal:output_type -> api.pledge.v1.KillAnimalReply
	14, // 16: api.pledge.v1.Animal.FeedingAnimal:output_type -> api.pledge.v1.FeedingAnimalReply
	16, // 17: api.pledge.v1.Animal.ComposeAnimal:output_type -> api.pledge.v1.ComposeAnimalReply
	10, // [10:18] is the sub-list for method output_type
	2,  // [2:10] is the sub-list for method input_type
	2,  // [2:2] is the sub-list for extension type_name
	2,  // [2:2] is the sub-list for extension extendee
	0,  // [0:2] is the sub-list for field type_name
}

func init() { file_api_pledge_v1_animal_proto_init() }
func file_api_pledge_v1_animal_proto_init() {
	if File_api_pledge_v1_animal_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pledge_v1_animal_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeleteAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AnimalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*KillAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedingAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*FeedingAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeAnimalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_animal_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ComposeAnimalReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pledge_v1_animal_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pledge_v1_animal_proto_goTypes,
		DependencyIndexes: file_api_pledge_v1_animal_proto_depIdxs,
		MessageInfos:      file_api_pledge_v1_animal_proto_msgTypes,
	}.Build()
	File_api_pledge_v1_animal_proto = out.File
	file_api_pledge_v1_animal_proto_rawDesc = nil
	file_api_pledge_v1_animal_proto_goTypes = nil
	file_api_pledge_v1_animal_proto_depIdxs = nil
}
