// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.7
// source: api/pledge/v1/pledge.proto

package v1

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreatePledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
	Price   int64  `protobuf:"varint,2,opt,name=price,proto3" json:"price,omitempty"`
}

func (x *CreatePledgeRequest) Reset() {
	*x = CreatePledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePledgeRequest) ProtoMessage() {}

func (x *CreatePledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePledgeRequest.ProtoReflect.Descriptor instead.
func (*CreatePledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{0}
}

func (x *CreatePledgeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *CreatePledgeRequest) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

type CreatePledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32  `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
}

func (x *CreatePledgeReply) Reset() {
	*x = CreatePledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePledgeReply) ProtoMessage() {}

func (x *CreatePledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePledgeReply.ProtoReflect.Descriptor instead.
func (*CreatePledgeReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{1}
}

func (x *CreatePledgeReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CreatePledgeReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type UpdatePledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePledgeRequest) Reset() {
	*x = UpdatePledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePledgeRequest) ProtoMessage() {}

func (x *UpdatePledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePledgeRequest.ProtoReflect.Descriptor instead.
func (*UpdatePledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{2}
}

type UpdatePledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UpdatePledgeReply) Reset() {
	*x = UpdatePledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdatePledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePledgeReply) ProtoMessage() {}

func (x *UpdatePledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePledgeReply.ProtoReflect.Descriptor instead.
func (*UpdatePledgeReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{3}
}

type DeletePledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePledgeRequest) Reset() {
	*x = DeletePledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePledgeRequest) ProtoMessage() {}

func (x *DeletePledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePledgeRequest.ProtoReflect.Descriptor instead.
func (*DeletePledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{4}
}

type DeletePledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *DeletePledgeReply) Reset() {
	*x = DeletePledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DeletePledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeletePledgeReply) ProtoMessage() {}

func (x *DeletePledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeletePledgeReply.ProtoReflect.Descriptor instead.
func (*DeletePledgeReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{5}
}

type PledgeInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id      int32  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	TokenId int32  `protobuf:"varint,2,opt,name=token_id,json=tokenId,proto3" json:"token_id,omitempty"`
	Price   int64  `protobuf:"varint,3,opt,name=price,proto3" json:"price,omitempty"`
	Status  int32  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	Times   int32  `protobuf:"varint,5,opt,name=times,proto3" json:"times,omitempty"`
	Address string `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *PledgeInfo) Reset() {
	*x = PledgeInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PledgeInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PledgeInfo) ProtoMessage() {}

func (x *PledgeInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PledgeInfo.ProtoReflect.Descriptor instead.
func (*PledgeInfo) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{6}
}

func (x *PledgeInfo) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PledgeInfo) GetTokenId() int32 {
	if x != nil {
		return x.TokenId
	}
	return 0
}

func (x *PledgeInfo) GetPrice() int64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *PledgeInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *PledgeInfo) GetTimes() int32 {
	if x != nil {
		return x.Times
	}
	return 0
}

func (x *PledgeInfo) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetPledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address string `protobuf:"bytes,1,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetPledgeRequest) Reset() {
	*x = GetPledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPledgeRequest) ProtoMessage() {}

func (x *GetPledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPledgeRequest.ProtoReflect.Descriptor instead.
func (*GetPledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{7}
}

func (x *GetPledgeRequest) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type GetPledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code int32       `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Msg  string      `protobuf:"bytes,2,opt,name=msg,proto3" json:"msg,omitempty"`
	Data *PledgeInfo `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *GetPledgeReply) Reset() {
	*x = GetPledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetPledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPledgeReply) ProtoMessage() {}

func (x *GetPledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPledgeReply.ProtoReflect.Descriptor instead.
func (*GetPledgeReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{8}
}

func (x *GetPledgeReply) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPledgeReply) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

func (x *GetPledgeReply) GetData() *PledgeInfo {
	if x != nil {
		return x.Data
	}
	return nil
}

type ListPledgeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPledgeRequest) Reset() {
	*x = ListPledgeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPledgeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPledgeRequest) ProtoMessage() {}

func (x *ListPledgeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPledgeRequest.ProtoReflect.Descriptor instead.
func (*ListPledgeRequest) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{9}
}

type ListPledgeReply struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ListPledgeReply) Reset() {
	*x = ListPledgeReply{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_pledge_v1_pledge_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ListPledgeReply) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListPledgeReply) ProtoMessage() {}

func (x *ListPledgeReply) ProtoReflect() protoreflect.Message {
	mi := &file_api_pledge_v1_pledge_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListPledgeReply.ProtoReflect.Descriptor instead.
func (*ListPledgeReply) Descriptor() ([]byte, []int) {
	return file_api_pledge_v1_pledge_proto_rawDescGZIP(), []int{10}
}

var File_api_pledge_v1_pledge_proto protoreflect.FileDescriptor

var file_api_pledge_v1_pledge_proto_rawDesc = []byte{
	0x0a, 0x1a, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x2f,
	0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x61, 0x70,
	0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x1a, 0x1c, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x45, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x39, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73, 0x67, 0x22, 0x15, 0x0a, 0x13, 0x55,
	0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x22, 0x13, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64,
	0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x15, 0x0a, 0x13, 0x44, 0x65, 0x6c, 0x65, 0x74,
	0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x13,
	0x0a, 0x11, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x22, 0x95, 0x01, 0x0a, 0x0a, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x49, 0x6e,
	0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02,
	0x69, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x49, 0x64, 0x12, 0x14, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x05, 0x70, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x74,
	0x69, 0x6d, 0x65, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x74, 0x69, 0x6d, 0x65,
	0x73, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x06, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x2c, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x65, 0x0a, 0x0e, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x12, 0x0a, 0x04, 0x63,
	0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x12,
	0x10, 0x0a, 0x03, 0x6d, 0x73, 0x67, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6d, 0x73,
	0x67, 0x12, 0x2d, 0x0a, 0x04, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x19, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61,
	0x22, 0x13, 0x0a, 0x11, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x11, 0x0a, 0x0f, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x32, 0xd6, 0x03, 0x0a, 0x06, 0x50, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x12, 0x68, 0x0a, 0x0c, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x12, 0x82, 0xd3, 0xe4, 0x93, 0x02,
	0x0c, 0x22, 0x07, 0x2f, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x3a, 0x01, 0x2a, 0x12, 0x54, 0x0a,
	0x0c, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x22, 0x2e,
	0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x70,
	0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65,
	0x70, 0x6c, 0x79, 0x12, 0x54, 0x0a, 0x0c, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x12, 0x22, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x65, 0x6c, 0x65, 0x74, 0x65, 0x50, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x12, 0x66, 0x0a, 0x09, 0x47, 0x65, 0x74,
	0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12, 0x1f, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65,
	0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1d, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c,
	0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x47, 0x65, 0x74, 0x50, 0x6c, 0x65, 0x64, 0x67,
	0x65, 0x52, 0x65, 0x70, 0x6c, 0x79, 0x22, 0x19, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x13, 0x12, 0x11,
	0x2f, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x7b, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x7d, 0x12, 0x4e, 0x0a, 0x0a, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x12,
	0x20, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1e, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x4c, 0x69, 0x73, 0x74, 0x50, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x52, 0x65, 0x70, 0x6c,
	0x79, 0x42, 0x2e, 0x0a, 0x0d, 0x61, 0x70, 0x69, 0x2e, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2e,
	0x76, 0x31, 0x50, 0x01, 0x5a, 0x1b, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x77, 0x6f, 0x72, 0x6c, 0x64,
	0x2f, 0x61, 0x70, 0x69, 0x2f, 0x70, 0x6c, 0x65, 0x64, 0x67, 0x65, 0x2f, 0x76, 0x31, 0x3b, 0x76,
	0x31, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_pledge_v1_pledge_proto_rawDescOnce sync.Once
	file_api_pledge_v1_pledge_proto_rawDescData = file_api_pledge_v1_pledge_proto_rawDesc
)

func file_api_pledge_v1_pledge_proto_rawDescGZIP() []byte {
	file_api_pledge_v1_pledge_proto_rawDescOnce.Do(func() {
		file_api_pledge_v1_pledge_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_pledge_v1_pledge_proto_rawDescData)
	})
	return file_api_pledge_v1_pledge_proto_rawDescData
}

var file_api_pledge_v1_pledge_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_api_pledge_v1_pledge_proto_goTypes = []interface{}{
	(*CreatePledgeRequest)(nil), // 0: api.pledge.v1.CreatePledgeRequest
	(*CreatePledgeReply)(nil),   // 1: api.pledge.v1.CreatePledgeReply
	(*UpdatePledgeRequest)(nil), // 2: api.pledge.v1.UpdatePledgeRequest
	(*UpdatePledgeReply)(nil),   // 3: api.pledge.v1.UpdatePledgeReply
	(*DeletePledgeRequest)(nil), // 4: api.pledge.v1.DeletePledgeRequest
	(*DeletePledgeReply)(nil),   // 5: api.pledge.v1.DeletePledgeReply
	(*PledgeInfo)(nil),          // 6: api.pledge.v1.PledgeInfo
	(*GetPledgeRequest)(nil),    // 7: api.pledge.v1.GetPledgeRequest
	(*GetPledgeReply)(nil),      // 8: api.pledge.v1.GetPledgeReply
	(*ListPledgeRequest)(nil),   // 9: api.pledge.v1.ListPledgeRequest
	(*ListPledgeReply)(nil),     // 10: api.pledge.v1.ListPledgeReply
}
var file_api_pledge_v1_pledge_proto_depIdxs = []int32{
	6,  // 0: api.pledge.v1.GetPledgeReply.data:type_name -> api.pledge.v1.PledgeInfo
	0,  // 1: api.pledge.v1.Pledge.CreatePledge:input_type -> api.pledge.v1.CreatePledgeRequest
	2,  // 2: api.pledge.v1.Pledge.UpdatePledge:input_type -> api.pledge.v1.UpdatePledgeRequest
	4,  // 3: api.pledge.v1.Pledge.DeletePledge:input_type -> api.pledge.v1.DeletePledgeRequest
	7,  // 4: api.pledge.v1.Pledge.GetPledge:input_type -> api.pledge.v1.GetPledgeRequest
	9,  // 5: api.pledge.v1.Pledge.ListPledge:input_type -> api.pledge.v1.ListPledgeRequest
	1,  // 6: api.pledge.v1.Pledge.CreatePledge:output_type -> api.pledge.v1.CreatePledgeReply
	3,  // 7: api.pledge.v1.Pledge.UpdatePledge:output_type -> api.pledge.v1.UpdatePledgeReply
	5,  // 8: api.pledge.v1.Pledge.DeletePledge:output_type -> api.pledge.v1.DeletePledgeReply
	8,  // 9: api.pledge.v1.Pledge.GetPledge:output_type -> api.pledge.v1.GetPledgeReply
	10, // 10: api.pledge.v1.Pledge.ListPledge:output_type -> api.pledge.v1.ListPledgeReply
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_api_pledge_v1_pledge_proto_init() }
func file_api_pledge_v1_pledge_proto_init() {
	if File_api_pledge_v1_pledge_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_pledge_v1_pledge_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdatePledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DeletePledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PledgeInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetPledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPledgeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_pledge_v1_pledge_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ListPledgeReply); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_pledge_v1_pledge_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_pledge_v1_pledge_proto_goTypes,
		DependencyIndexes: file_api_pledge_v1_pledge_proto_depIdxs,
		MessageInfos:      file_api_pledge_v1_pledge_proto_msgTypes,
	}.Build()
	File_api_pledge_v1_pledge_proto = out.File
	file_api_pledge_v1_pledge_proto_rawDesc = nil
	file_api_pledge_v1_pledge_proto_goTypes = nil
	file_api_pledge_v1_pledge_proto_depIdxs = nil
}
